title: Endorphin 3D
description: The Ender 5 as it should be
theme: just-the-docs

url: https://endorphin3d.com
logo: "/assets/images/logo-text.png"
favicon_ico: "/assets/images/logo.svg"

aux_links:
  Repository: https://github.com/endorphin3d/endorphin

color_scheme: endorphin

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "assets/vids"
    values:
      video: true

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red